services:
  tanumsgfowarder:
    build: .
    image: ghcr.io/hariomop12/tanumsgfowarder:latest
    container_name: tanumsgfowarder
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .wwebjs_auth:/app/.wwebjs_auth
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
